version: v1

labels:
  - label: 'maintenance'
    sync: true
    matcher:
      title: '^(build|chore|ci|refactor|style|test)(\([a-z][a-z0-9-]*\))?!?: .+'

  - label: 'documentation'
    sync: true
    matcher:
      title: '^(docs)(\([a-z][a-z0-9-]*\))?!?: .+'

  - label: 'enhancement'
    sync: true
    matcher:
      title: '^(feat|perf)(\([a-z][a-z0-9-]*\))?!?: .+'

  - label: 'bugfix'
    sync: true
    matcher:
      title: '^(fix)(\([a-z][a-z0-9-]*\))?!?: .+'

  - label: 'breaking'
    sync: true
    matcher:
      title: '^[a-z]+!(\([a-z][a-z0-9-]*\))?!?: .+'

  - label: 'dependencies'
    sync: true
    matcher:
      files:
        any:
          - "pkg/versionconstants/**"
          - "go.*"
          - "vendor/**"

checks:
  - context: "Semantic Pull Request"
    url: "https://ddev.readthedocs.io/en/latest/developers/building-contributing/#pull-request-title-guidelines"
    description:
      success: Ready for review.
      failure: Missing semantic label.
    labels:
      any:
        - bugfix
        - documentation
        - enhancement
        - maintenance
