#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Run HeidiSQL against current db
## Usage: heidisql [database] [user] [password] [nettype] [library]
## Example: "ddev heidisql" or "ddev heidisql db db db 8 libpq-12.dll"
## OSTypes: windows,wsl2,linux
## HostBinaryExists: /mnt/c/Program Files/HeidiSQL/heidisql.exe,C:\Program Files\HeidiSQL\Heidisql.exe,/usr/bin/heidisql,/usr/local/bin/heidisql,/snap/bin/heidisql-wine

if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start || exit $?
  no_recursion=true ddev "$(basename "$0")" "$@"
  exit $?
fi

db_name="${1:-db}"
db_user="${2:-root}"
db_password="${3:-root}"
db_network_type="${4:-0}" # Default: MySQL/MariaDB
db_library="${5:-libmariadb.dll}"

db_type="$(echo "$DDEV_DATABASE" | sed 's/:.*//')"
db_version=$(yq e '.database.version' .ddev/config.yaml 2>/dev/null || echo "")

if [ "$db_type" = "postgres" ]; then
  db_network_type="8"
  db_user="db"
  db_password="db"
  if [ -z "$5" ]; then
    db_library="libpq-${db_version:-12}.dll"
  fi
fi

arguments=(
  "--host=127.0.0.1"
  "--port=${DDEV_HOST_DB_PORT}"
  "--user=${db_user}"
  "--password=${db_password}"
  "--database=${db_name}"
  "--description=${DDEV_SITENAME}"
  "--nettype=${db_network_type}"
  "--library=${db_library}"
)

case $OSTYPE in
  "win"* | "msys"*)
    start "" "C:\Program Files\HeidiSQL\heidisql.exe" "${arguments[@]}" &
    ;;
  "linux-gnu")
    BINARIES=(
      /usr/local/bin/heidisql
      /usr/bin/heidisql
      /snap/bin/heidisql-wine
      "/mnt/c/Program Files/HeidiSQL/heidisql.exe"
    )
    for binary in "${BINARIES[@]}"; do
      if [ -x "$binary" ]; then
        "$binary" "${arguments[@]}" &>/dev/null & disown
        exit 0
      fi
    done
    ;;
esac
