#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Run HeidiSQL against current db
## Usage: heidisql [database]
## Example: "ddev heidisql" or "ddev heidisql my_other_db"
## OSTypes: windows,wsl2,linux
## HostBinaryExists: /mnt/c/Program Files/HeidiSQL/heidisql.exe,C:\Program Files\HeidiSQL\Heidisql.exe,/usr/bin/heidisql,/usr/local/bin/heidisql,/snap/bin/heidisql-wine

if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start || exit $?
  no_recursion=true ddev "$(basename "$0")" "$@"
  exit $?
fi

arguments=(
  "--host=127.0.0.1"
  "--port=${DDEV_HOST_DB_PORT}"
  "--user=root"
  "--password=root"
  "--description=${DDEV_SITENAME}"
)

case $OSTYPE in
  "win"* | "msys"*)
    start "" "C:\Program Files\HeidiSQL\heidisql.exe" "${arguments[@]}" &
    ;;
  "linux-gnu")
    BINARIES=(
      /usr/local/bin/heidisql
      /usr/bin/heidisql
      /snap/bin/heidisql-wine
      "/mnt/c/Program Files/HeidiSQL/heidisql.exe"
    )

    for binary in "${BINARIES[@]}"; do
      if [ -x "$binary" ]; then
        echo "Launching $binary"
        "$binary" "${arguments[@]}" &>/dev/null & disown
        exit 0
      fi
    done
    ;;
esac
