#!/bin/bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Prompt downloading phpMyAdmin if it is not installed.
## Usage: phpmyadmin
## Example: "ddev phpmyadmin"

if [ "${DDEV_PROJECT_STATUS-running}" != "running" ] && [ -z "$no_recursion" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start
  start_exit_code=$?
  if [ $start_exit_code -ne 0 ]; then
    exit $start_exit_code
  fi
  # run this script again, as the environment is updated after "ddev start"
  no_recursion=true ddev "$(basename "$0")" "$@"
  exit $?
fi

read -p "phpMyAdmin is not installed would you like to install? (yes/no): " answer

case "$answer" in
    [Yy] | [Yy][Ee][Ss])
        ddev get ddev/ddev-phpmyadmin
        echo "phpMyAdmin has been installed and requires a restart."
        read -p "Would you like me to restart now? (yes/no): " answerrestart
        case "$answerrestart" in
            [Yy] | [Yy][Ee][Ss])
                ddev restart
                echo "Run ddev phpmyadmin again to use it."
                ;;
            *)
                echo "You must manually restart ddev to use phpMyAdmin ddev restart."
                ;;
        esac
        ;;
    *)
        echo "Nothing has been changed."
        ;;
esac

if [[ "$answer" == "yes" ]]; then
    ddev get ddev/ddev-phpmyadmin
    echo "phpMyAdmin has been installed and requires a restart."
    read -p "Would you like me to restart now? (yes/no): " answerrestart
    if [[ "answerrestart" == "yes" ]]; then
      ddev restart
      echo "Run ddev phpmyadmin again to use it."
    else
      echo "You must manually restart ddev to use phpMyAdmin ddev restart."
    fi
elif [[ "$answer" == "no" ]]; then
    echo "Nothing has been changed."
else
    echo "Please enter yes or no."
fi
