#!/bin/bash
#ddev-generated

## Description: Run Symphony phpunit tests
## Usage: phpunit <test>
## Example: "ddev phpunit" or "ddev phpunit tests/Util"
CWD=$(pwd)

ddev . ./vendor/bin/phpunit "$@" | sed "2,\$s|/var/www/html|$CWD|"
