#!/bin/bash

## #ddev-generated
## Description: Helper function to launch a browser to the project URL based on the port.
## Usage: port [number] [-p|--https-port number] [-P|--http-port number]
## Example: "ddev port 3000" (prefer HTTPS) or "ddev port -p 3000" (prefer HTTPS) or "ddev port -P 3000" (prefer HTTP)
## Flags: [{"Name":"http-port","Shorthand":"P","Usage":"ddev launch -P 3000 for HTTP port, has priority over the port argument"}, {"Name":"https-port","Shorthand":"p","Usage":"ddev launch -p 3000 for HTTPS port, has priority over the --http-port flag"}]

HTTP_PORT=
HTTPS_PORT=
HTTPS_PORT_AS_DEFAULT=$1

while [ $# -gt 0 ]; do
  case "$1" in
  -P | --http-port)
    # Set the default HTTP port.
    HTTP_PORT="$2"
    shift
    ;;
  -p | --https-port)
    # Set the default HTTPS port.
    HTTPS_PORT="$2"
    shift
    ;;
  --) shift ;;
  esac
  shift
done

if [ -n "$HTTP_PORT" ] && [ -z "$HTTPS_PORT" ]; then
  ddev launch --http-port $HTTP_PORT
elif [ -z "$HTTP_PORT" ] && [ -n "$HTTPS_PORT" ]; then
  ddev launch --https-port $HTTPS_PORT
elif [ -n "$HTTP_PORT" ] && [ -n "$HTTPS_PORT" ]; then
  ddev launch --http-port $HTTP_PORT --https-port $HTTPS_PORT
else
  ddev launch --https-port $HTTPS_PORT_AS_DEFAULT
fi
