#!/usr/bin/env bash

#ddev-generated
# Support for Querious, https://www.araelium.com/querious
## Description: Run querious with current project database
## Usage: querious [database]
## Example: "ddev querious"
## OSTypes: darwin
## HostBinaryExists: /Applications/Querious.app
## DBTypes: mysql,mariadb

if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start
  start_exit_code=$?
  if [ $start_exit_code -ne 0 ]; then
    exit $start_exit_code
  fi
  # run this script again, as the environment is updated after "ddev start"
  no_recursion=true ddev "$(basename "$0")" "$@"
  exit $?
fi
DATABASE="${1:-db}"

open "querious://connect/new?host=127.0.0.1&user=db&password=db&use-compression=false&database=${DATABASE}&port=${DDEV_HOST_DB_PORT}"
