#!/bin/bash

#ddev-generated
## Description: Run sequelace with current project database
## Usage: sequelace
## Example: "ddev sequelace" or "ddev sequelace database2" to open a database named "database2".
## OSTypes: darwin
## HostBinaryExists: /Applications/Sequel ace.app
## DBTypes: mysql,mariadb

DATABASE="${1:-db}"

if [ "${DDEV_PROJECT_STATUS}" != "running" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start
fi
query="mysql://root:root@${DDEV_PROJECT}.${DDEV_TLD}:${DDEV_HOST_DB_PORT}/${DATABASE}"

set -x
open "$query" -a "/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace"

