image: drud/ddev-gitpod-base:20211028_new_host_docker_internal_detection

experimentalNetwork: true
tasks:
  - name: ddev
  - name: demand-setup
    command: |
      if [ ! -z ${REPO} ]; then
        mkdir /workspace/repo
        git clone ${REPO} /workspace/repo --branch=${BRANCH}
        ddev config global --omit-containers=ddev-router,dba,ddev-ssh-agent
        if [ ! -f .ddev/config.yaml ]; then
          ddev config --auto
        fi
        echo <<<END >.ddev/config.gitpod.yaml 
          host_http_port: 8080
          bind-all-interfaces: true
        END
          
      fi
  - name: simpleproj
    init: |
      # Compile ddev
      make

      # Configure ddev to run on Gitpod
      export DDEV_NONINTERACTIVE=true
      ddev config global --omit-containers=ddev-router,ddev-ssh-agent,dba

      # Configure ddev Drupal project
      mkdir -p /workspace/simpleproj && cd /workspace/simpleproj
      ddev config --project-type=drupal9 --docroot=web --create-docroot

      gitpod-setup-ddev.sh /workspace/simpleproj

      mkcert -install

      # Download ddev's docker images
      ddev debug download-images

      # Create 'simpleproj' - Umami demo on latest stable Drupal version
      ddev start -y
      ddev composer create drupal/recommended-project -y && ddev composer require drush/drush
      ddev drush si demo_umami -y --account-pass=admin

    command: |
      # Configure ddev to run on Gitpod
      export DDEV_NONINTERACTIVE=true
      ddev config global --omit-containers=ddev-router,ddev-ssh-agent,dba
      gitpod-setup-ddev.sh /workspace/simpleproj

      # Start ddev
      cd /workspace/simpleproj
      ddev start -y
      gp await-port 8080 && sleep 1 && gp preview $(gp url 8080)

vscode:
  extensions:
    # Go extension
    - golang.go

    # PHP extension
    - felixfbecker.php-debug

    # Bash extensions
    - timonwong.shellcheck
    - rogalmic.bash-debug

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

ports:
  # Ignore direct-build https port
  - port: 2222
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Currently un-notified and unsupported mailhog http port
  - port: 8025
    onOpen: ignore
  # Currently un-notified and unsupported mailhog https port
  - port: 8026
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
  # router http port that we're ignoring.
  - port: 8888
    onOpen: ignore
  # router https port that we're ignoring.
  - port: 8889
    onOpen: ignore
  # xdebug port
  - port: 9000
    onOpen: ignore
  # projector port
  - port: 9999
