image: ddev/ddev-gitpod-base:20231030
tasks:
  - name: build-run
    init: |
      # Compile ddev
      make
      ddev debug download-images
      mkcert -install
    command: |
      export DDEV_NONINTERACTIVE=true
      DDEV_REPO=${DDEV_REPO:-https://github.com/ddev/d10simple}
      DDEV_ARTIFACTS=${DDEV_REPO}-artifacts
      git clone ${DDEV_ARTIFACTS} "/tmp/${DDEV_ARTIFACTS##*/}" || true
      reponame=${DDEV_REPO##*/}
      mkdir -p /workspace/${reponame} && cd /workspace/${reponame}
      if [ ! -d /workspace/${reponame}/.git ]; then
        git clone ${DDEV_REPO} /workspace/${reponame}
      fi
      if [ ! -f .ddev/config.yaml ]; then
        ddev config --auto
      fi
      ddev stop -a
      ddev start -y
      if [ -d "/tmp/${DDEV_ARTIFACTS##*/}" ]; then
        ddev import-db --file=/tmp/${DDEV_ARTIFACTS##*/}/db.sql.gz
        ddev import-files --source=/tmp/${DDEV_ARTIFACTS##*/}/files.tgz
      fi
      gp ports await 8080 && sleep 1 && gp preview $(gp url 8080)

vscode:
  extensions:
    # Go extension
    - golang.go

    # PHP extension
    - felixfbecker.php-debug

    # Bash extensions
    - timonwong.shellcheck
    - rogalmic.bash-debug

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

ports:
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Currently un-notified and unsupported mailpit https port
  - port: 8027
    onOpen: ignore
  - port: 8036
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
