image:
  file: .gitpod.Dockerfile

tasks:
  - name: terminal
    init: |
      export DDEV_NONINTERACTIVE=true
      make
      mkdir -p /workspace/simpleproj && cd /workspace/simpleproj
      ddev config --project-type=drupal9 --docroot=web --create-docroot
      ddev composer create drupal/recommended-project -y && ddev composer require drush/drush
      cp ~/bin/gitpod-setup-ddev.sh .ddev && .ddev/gitpod-setup-ddev.sh
    command: |
      cd /workspace/simpleproj && .ddev/gitpod-setup-ddev.sh
      gp await-port 8080 && sleep 1 && gp preview $(gp url 8080)

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
