image: ddev/ddev-gitpod-base:latest
tasks:
  - name: build-run
    init: |
      # Compile ddev
      make
      ddev config global --omit-containers=ddev-router
      ddev debug download-images
      mkcert -install
    command: |
      export DDEV_NONINTERACTIVE=true
      DDEV_REPO=${DDEV_REPO:-https://github.com/ddev/d10simple}
      DDEV_ARTIFACTS=${DDEV_REPO}-artifacts
      git clone ${DDEV_ARTIFACTS} "/tmp/${DDEV_ARTIFACTS##*/}" || true
      reponame=${DDEV_REPO##*/}
      mkdir -p /workspace/${reponame} && cd /workspace/${reponame}
      if [ ! -d /workspace/${reponame}/.git ]; then
        git clone ${DDEV_REPO} /workspace/${reponame}
      fi
      if [ ! -f .ddev/config.yaml ]; then
        ddev config --auto
      fi
      ddev stop -a
      ddev start -y
      if [ -d "/tmp/${DDEV_ARTIFACTS##*/}" ]; then
        ddev import-db --file=/tmp/${DDEV_ARTIFACTS##*/}/db.sql.gz
        ddev import-files --source=/tmp/${DDEV_ARTIFACTS##*/}/files.tgz
      fi
      gp ports await 8080 && sleep 1 && gp preview $(gp url 8080)
      unset DDEV_NONINTERACTIVE

vscode:
  extensions:
    # Go extension
    - golang.go

    # PHP extension
    - felixfbecker.php-debug

    # Bash extensions
    - timonwong.shellcheck
    - rogalmic.bash-debug

ports:
  # Ignore direct-build https port
  - port: 2222
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Currently un-notified and unsupported mailpit https port
  - port: 8027
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # xhgui http port
  - port: 8143
    onOpen: ignore
  # xhgui https port
  - port: 8142
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
  # Adminer http port
  - port: 9100
    onOpen: ignore
  # Adminer https port
  - port: 9101
    onOpen: ignore
  # projector port
  - port: 9999
