# See https://golangci-lint.run/
version: "2"
run:
  modules-download-mode: vendor
  timeout: 30m
output:
  formats:
    text:
      path: stdout
      colors: true
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - whitespace
    # Enable these when working on test refactoring
    #- testifylint
    #- usetesting
  settings:
    staticcheck:
      checks:
        - all
        - -QF1001 # Apply De Morgan's law
        - -QF1003 # Convert if/else-if chain to tagged switch
        - -S1008 # Simplify returning boolean expression
        - -S1023 # Omit redundant control flow
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party/ampli/ampli.go
formatters:
  enable:
    - gofmt
