builds:
- id: ddev
  # Requires make  darwin_amd64 darwin_arm64 linux_amd64 linux_arm64 windows_amd64 mkcert
  builder: prebuilt
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  goamd64:
    - v1
  ignore:
    - goos: windows
      goarch: arm64
  prebuilt:
    path: .gotmp/bin/{{.Os}}_{{.Arch}}/ddev{{.Ext}}
  binary: ddev

- id: mkcert
  # requires make completions
  builder: prebuilt
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - arm64
  - amd64
  goamd64:
  - v1
  ignore:
  - goos: windows
    goarch: arm64
  prebuilt:
    path: .gotmp/bin/{{.Os}}_{{.Arch}}/mkcert{{.Ext}}
  binary: mkcert

- id: completions-tarball
  # requires make completions
  builder: prebuilt
  goos:
  - linux
  goarch:
  - arm64
  prebuilt:
    path: .gotmp/bin/completions.tar.gz
  binary: completions.tar.gz

- id: ddev_bash_completion.sh
  # requires make completions
  builder: prebuilt
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - arm64
  - amd64
  goamd64:
  - v1
  prebuilt:
    path: .gotmp/bin/completions/ddev_bash_completion.sh
  binary: ddev_bash_completion.sh

- id: ddev_zsh_completion.sh
  # requires make completions
  builder: prebuilt
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - arm64
  - amd64
  goamd64:
  - v1
  prebuilt:
    path: .gotmp/bin/completions/ddev_zsh_completion.sh
  binary: ddev_zsh_completion.sh

- id: ddev_fish_completion.sh
  # requires make completions
  builder: prebuilt
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - arm64
  - amd64
  goamd64:
  - v1
  prebuilt:
    path: .gotmp/bin/completions/ddev_fish_completion.sh
  binary: ddev_fish_completion.sh

- id: ddev-windows-installer
  builder: prebuilt
  goos:
  - windows
  goarch:
  - amd64
  goamd64:
  - v1
  prebuilt:
    path: .gotmp/bin/windows_amd64/ddev_windows_installer.exe
  binary: ddev-windows-installer.exe


archives:
- id: ddev
  builds:
  - ddev
  - mkcert
  - ddev_bash_completion.sh
  - ddev_zsh_completion.sh
  - ddev_fish_completion.sh
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}.v{{ .Version }}"
  replacements:
    darwin: macos
  format_overrides:
  - goos: windows
    format: zip
  wrap_in_directory: false
  files:
  - LICENSE
  - .gotmp/bin/{{.Os}}_{{.Arch}}/mkcert*
  allow_different_binary_count: true

- id: completions-tarball
  builds:
  - completions
  format: binary
  name_template: ddev_shell_completion_scripts.v{{.Version}}.tar.gz
#  files:
#    - .gotmp/bin/completions.tar.gz

- id: ddev-windows-installer
  builds:
  - ddev-windows-installer
  format: binary
  name_template: "ddev_windows_installer.v{{.Version}}"

#  files:
#  - none*
#  files:
#  - LICENSE


checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  github:
    owner: rfay
    name: ddev

brews:
- name: ddev
  ids:
  - ddev
  tap:
    owner: rfay
    name: homebrew-ddev-edge
  description: DDEV
  folder: Formula
  homepage: https://ddev.com
  license: "Apache 2"
  dependencies:
  - name: mkcert
  custom_block: |
    head "https://github.com/drud/ddev.git", branch: "master"
    depends_on "go" => :build
    depends_on "make" => :build

#  install: |
#    system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
#    system "cp", ".gotmp/bin/darwin_arm64/ddev", "#{bin}/ddev"

  test: |
    system "#{bin}/ddev --version"


nfpms:
- maintainer: Randy Fay
  license: "Apache 2"
  formats:
  - deb
  - rpm

snapshot:
  name_template: '{{ .Version }}-{{.ShortCommit}}'
