builds:
- id: ddev
  builder: prebuilt
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  goamd64:
    - v1
  ignore:
    - goos: windows
      goarch: arm64
  prebuilt:
    path: .gotmp/bin/{{.Os}}_{{.Arch}}/ddev{{.Ext}}
  binary: ddev

- id: completions
  builder: prebuilt
  goos:
  - linux
  goarch:
  - arm64
  prebuilt:
    path: .gotmp/bin/completions.tar.gz
  binary: completions.tar.gz

- id: ddev-windows-installer
  builder: prebuilt
  goos:
  - windows
  goarch:
  - amd64
  goamd64:
  - v1
  prebuilt:
    path: .gotmp/bin/windows_amd64/ddev_windows_installer.exe
  binary: ddev-windows-installer.exe


archives:
- id: ddev
  builds:
  - ddev
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}.v{{ .Version }}"
  replacements:
    darwin: macos
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE

- id: completions
  builds:
  - completions
  format: binary
#  files:
#    - .gotmp/bin/completions.tar.gz

- id: ddev-windows-installer
  builds:
  - ddev-windows-installer
  format: binary
#  files:
#  - none*
#  files:
#  - LICENSE


checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  github:
    owner: rfay
    name: ddev

brews:
- name: ddev
  ids:
  - ddev
  tap:
    owner: rfay
    name: homebrew-ddev-edge
  description: DDEV
  folder: Formula
  homepage: https://ddev.com
  license: "Apache 2"
  dependencies:
  - name: mkcert
  custom_block: |
    head "https://github.com/drud/ddev.git", branch: "master"
    depends_on "go" => :build
    depends_on "make" => :build

#  install: |
#    system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
#    system "cp", ".gotmp/bin/darwin_arm64/ddev", "#{bin}/ddev"

  test: |
    system "#{bin}/ddev --version"


nfpms:
- maintainer: Randy Fay
  license: "Apache 2"
  formats:
  - deb
  - rpm




