dirs:
  - docs/content
ignorePatterns:
  - pattern: '^https*://127.0.0.1'
  - pattern: '^https://www.drupal.org/(u|project|about|forum|slack|join-slack)'
  - pattern: "^https://deb.sury.org"
  - pattern: "^https://nssm.cc/"
  - pattern: "^https://www.php.net/manual/"
  - pattern: "^https://www.drupaleasy.com/blogs/ultimike/2019/06/sharing-your-ddev-local-site-public-url-using-ddev-share-and-ngrok"
  - pattern: "^https://.*blackfire.io"
  - pattern: "^https://twitter.com/search"
  - pattern: "^https://www.cyberciti.biz/"
  - pattern: "^https://nightly.link/ddev/ddev/workflows/master-build/main"
  - pattern: "^https://github.com/ddev/maintainer-info"
  - pattern: "^https://buildkite.com/organizations/ddev"
  - pattern: "^https://github.com/orgs/ddev"
  - pattern: "^https://github.com/watching"
  - pattern: "^https://newmonitor.thefays.us/icingaweb2"
  - pattern: "^https://analytics.amplitude.com"
  - pattern: "^https://(meta.stackoverflow|stackoverflow|superuser).com/"
  - pattern: "^https://packages.debian.org/stable/"
  - pattern: "^https://symfony.com"
  - pattern: "^https://community.chocolatey.org"
  - pattern: "^https://aur.archlinux.org"
  - pattern: "^https://team-ddev.1password.com"
  - pattern: "^https://.*.archive.org"
aliveStatusCodes:
  - 200
  - 206
  - 301

#modifiedFilesOnly: true


# Former config from https://github.com/gaurav-nelson/github-action-markdown-link-check:
#  "httpHeaders": [
#    {
#      "urls": ["https://github.com/", "https://guides.github.com/", "https://help.github.com/", "https://docs.github.com/"],
#      "headers": {
#        "Accept-Encoding": "zstd, br, gzip, deflate"
#      }
#    }
#  ],
#
#  "timeout": "20s",
#  "retryOn429": true,
#  "retryCount": 5,
#  "fallbackRetryDelay": "30s",
#  "aliveStatusCodes": [200, 206, 301]
#}
