dirs:
  - docs/content
ignorePatterns:
  # Ignore internal anchors that are already handled by mkdocs
  - pattern: ".md#"
  - pattern: "https://www.drupal.org/project/"
  - pattern: "https://www.drupal.org/forum/"
  - pattern: "https://www.drupal.org/join-slack"
  - pattern: "https://www.php.net/manual/"
  - pattern: "https://www.drupaleasy.com"
  - pattern: "https://blackfire.io"
  - pattern: "https://www.blackfire.io"
  - pattern: "https://nightly.link/ddev/ddev/workflows/main-build/main"
  - pattern: "https://github.com/ddev/maintainer-info"
  - pattern: "https://buildkite.com/organizations/ddev"
  - pattern: "https://github.com/orgs/ddev"
  - pattern: "https://github.com/watching"
  - pattern: "https://newmonitor.thefays.us/icingaweb2"
  - pattern: "https://analytics.amplitude.com"
  - pattern: "https://stackoverflow.com"
  - pattern: "https://meta.stackoverflow.com"
  - pattern: "https://superuser.com"
  - pattern: "https://symfony.com"
  - pattern: "https://community.chocolatey.org"
  - pattern: "https://aur.archlinux.org"
  - pattern: "https://team-ddev.1password.com"
  - pattern: "https://web.archive.org"
  - pattern: "https://specifications.freedesktop.org"
  - pattern: "https://mutagen.io"
aliveStatusCodes:
  - 200
  - 206
  - 301
  # TODO: GitHub changed its limits, now we get 429, remove this workaround when it is resolved
  # See https://github.com/UmbrellaDocs/action-linkspector/issues/43
  - 429
#modifiedFilesOnly: true
