matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .spellcheckwordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  - pyspelling.filters.url:
  sources:
  - 'docs/**/*.md|!docs/developers/*|!docs/users/topics/version-history.md'
  - 'docs/index.md'
  default_encoding: utf-8
