language: go

go:
- 1.x

arch: arm64-graviton2
virt: vm
os: linux
dist: focal
group: edge

before_install:
  - ./.travis/linux_travis_arm64_setup.sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

install:
  - docker buildx create --name ddev-builder-multi --use

jobs:
  include:
    - stage: test
      name: Run make test
      script: make test
    - name: Linux container tests
      script: |
        for dir in containers/*/
          do pushd $dir
          echo "--- Build container $dir"
          time make container DOCKER_ARGS=--no-cache
          echo "--- Test container $dir"
          time make test
          popd
        done
