package ddevapp

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/ddev/ddev/pkg/archive"
	"github.com/ddev/ddev/pkg/fileutil"
	"github.com/ddev/ddev/pkg/nodeps"
	"github.com/ddev/ddev/pkg/util"
	copy2 "github.com/otiai10/copy"
)

// modxSettings holds the values injected into the DDEV-managed
// core/config/config.inc.php template. Following the convention used by the
// WordPress and TYPO3 project types, the database name/user/password are the
// fixed DDEV literals `db`/`db`/`db` directly in the template; only the values
// that can legitimately vary are passed through this struct.
type modxSettings struct {
	DBHostname  string
	DBCharset   string
	TablePrefix string
	// HTTPHost is only used as the fallback host for CLI/API mode requests,
	// where $_SERVER['HTTP_HOST'] is not available. For web requests MODX
	// derives the host dynamically from $_SERVER, so the generated file works
	// regardless of the project's URL.
	HTTPHost string
}

// isModxApp returns true if the app is of type modx.
// core/docs/version.inc.php is present in every MODX Revolution codebase (2.x
// and 3.x, both in source checkouts and installed sites) and is uniquely MODX,
// which makes it a reliable signature. config.core.php is intentionally not
// used here: it is generated by the installer and is frequently absent (the
// entry scripts fall back to MODX_CORE_PATH = <docroot>/core/), so it would
// miss a freshly downloaded MODX codebase.
func isModxApp(app *DdevApp) bool {
	return fileutil.FileExists(filepath.Join(app.AppRoot, app.Docroot, "core", "docs", "version.inc.php"))
}

// modxHooks adds a MODX-specific hooks example.
const modxHooks = `# Un-comment to run composer install for a Composer-based MODX install.
#  post-start:
#    - exec: composer install -d /var/www/html
`

// getModxHooks for appending as byte array
func getModxHooks() []byte {
	return []byte(modxHooks)
}

// getModxUploadDirs returns the default paths, which is where user-uploaded
// media lives in MODX (assets/, including assets/uploads/). This is the
// `ddev import-files` target.
func getModxUploadDirs(_ *DdevApp) []string {
	return []string{"assets"}
}

// setModxSiteSettingsPaths sets the paths to settings files for templating.
// MODX loads core/config/<MODX_CONFIG_KEY>.inc.php. The default MODX_CONFIG_KEY
// is "config", so the default install uses core/config/config.inc.php. Non-default
// config keys exist but are rare, so DDEV manages the default. The core/ directory
// lives at the web root (docroot), so the path is resolved relative to the docroot.
func setModxSiteSettingsPaths(app *DdevApp) {
	settingsFilePath := filepath.Join(app.GetAbsDocroot(false), "core", "config", "config.inc.php")

	// MODX has a single config.inc.php that DDEV manages directly (there is no
	// separate additional-settings include like Drupal/TYPO3), so both paths
	// point at the same file.
	app.SiteSettingsPath = settingsFilePath
	app.SiteDdevSettingsFile = settingsFilePath
}

// createModxSettingsFile generates the DDEV-managed core/config/config.inc.php.
//
// A freshly extracted MODX codebase has no core/config/config.inc.php until the
// /setup/ installer runs. DDEV generates a complete, DB-connected config.inc.php
// (matching the behavior of the WordPress and TYPO3 types) so that a project
// with a pre-seeded database boots directly, including the /manager/ backend.
// The generated file is only written when it does not exist or is still
// ddev-managed (carries the #ddev-generated signature); a user who removes the
// signature to take the file over is never clobbered.
//
// The config.core.php stub files (at the web root and in core/, manager/ and
// connectors/) only define MODX_CORE_PATH and MODX_CONFIG_KEY (paths/keys, not
// database credentials) and are intentionally left alone.
func createModxSettingsFile(app *DdevApp) (string, error) {
	settings := modxSettings{
		DBHostname:  "db",
		DBCharset:   "utf8mb4",
		TablePrefix: "modx_",
		HTTPHost:    app.GetHostname(),
	}

	// If a config.inc.php already exists, only overwrite it when it is still
	// ddev-managed. Otherwise leave the user's file alone.
	if fileutil.FileExists(app.SiteSettingsPath) {
		sigExists, err := fileutil.FgrepStringInFile(app.SiteSettingsPath, nodeps.DdevFileSignature)
		if err != nil {
			return "", err
		}
		if !sigExists {
			util.Warning("%s already exists and is managed by the user.", filepath.Base(app.SiteSettingsPath))
			return app.SiteSettingsPath, nil
		}
	}

	if err := writeModxSettingsFile(settings, app.SiteSettingsPath); err != nil {
		return "", fmt.Errorf("failed to write MODX config.inc.php file: %v", err)
	}

	return app.SiteSettingsPath, nil
}

// writeModxSettingsFile produces a valid config.inc.php by combining the
// modxSettings object with the embedded data-driven template.
func writeModxSettingsFile(settings modxSettings, filePath string) error {
	t, err := template.New("config.inc.php").ParseFS(bundledAssets, "modx/config.inc.php")
	if err != nil {
		return err
	}

	// Ensure target directory exists and is writable
	dir := filepath.Dir(filePath)
	if err = util.Chmod(dir, 0755); os.IsNotExist(err) {
		if err = os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	} else if err != nil {
		return err
	}

	file, err := os.Create(filePath)
	if err != nil {
		return err
	}
	defer util.CheckClose(file)

	//nolint: revive
	if err = t.Execute(file, settings); err != nil {
		return err
	}

	return nil
}

// modxImportFilesAction defines the MODX workflow for importing project files
// into the upload dir. It is currently identical to the Drupal/TYPO3 workflow.
func modxImportFilesAction(app *DdevApp, uploadDir, importPath, extPath string) error {
	destPath := app.calculateHostUploadDirFullPath(uploadDir)

	// parent of destination dir should exist
	if !fileutil.FileExists(filepath.Dir(destPath)) {
		return fmt.Errorf("unable to import to %s: parent directory does not exist", destPath)
	}

	// parent of destination dir should be writable.
	if err := util.Chmod(filepath.Dir(destPath), 0755); err != nil {
		return err
	}

	// If the destination path exists, purge it as was warned
	if fileutil.FileExists(destPath) {
		if err := fileutil.PurgeDirectory(destPath); err != nil {
			return fmt.Errorf("failed to cleanup %s before import: %v", destPath, err)
		}
	}

	if isTar(importPath) {
		if err := archive.Untar(importPath, destPath, extPath); err != nil {
			return fmt.Errorf("failed to extract provided archive: %v", err)
		}

		return nil
	}

	if isZip(importPath) {
		if err := archive.Unzip(importPath, destPath, extPath); err != nil {
			return fmt.Errorf("failed to extract provided archive: %v", err)
		}

		return nil
	}

	if err := copy2.Copy(importPath, destPath); err != nil {
		return err
	}

	return nil
}
