services:
  ddev-router:
    image: {{ .router_image }}

    # Prevent zombie container
    init: true
    user: {{ .UID }}:{{ .GID }}

    networks:
      - ddev_default
    container_name: ddev-router
    ports: {{ $dockerIP := .dockerIP }}{{ if not .router_bind_all_interfaces }}{{ range $port := .ports }}
      - "{{ $dockerIP }}:{{ $port }}:{{ $port }}"{{ end }}{{ else }}{{ range $port := .ports }}
      - "{{ $port }}:{{ $port }}"{{ end }}{{ end }}
      # Traefik router; configured in static config as entrypoint
      - "{{ if not .router_bind_all_interfaces }}{{ $dockerIP }}:{{ end }}{{.TraefikMonitorPort}}:{{.TraefikMonitorPort}}"
    labels:
      # For cleanup on ddev poweroff
      com.ddev.site-name: ""
    volumes:
      - ddev-global-cache:/mnt/ddev-global-cache:rw
      {{ if .letsencrypt }}
      - ddev-router-letsencrypt:/etc/letsencrypt:rw
      {{ end }} {{/* end if .letsencrypt */}}
    environment:
      - TRAEFIK_MONITOR_PORT={{ .TraefikMonitorPort }}
        {{ if .letsencrypt }}
      - LETSENCRYPT_EMAIL={{ .letsencrypt_email }}
      - USE_LETSENCRYPT={{ .letsencrypt }}
        {{ end }}{{/* end if .letsencrypt */}}
      - TZ={{ .Timezone }}
      # Bypass proxies to allow internal container connections
      - NO_PROXY=*
      - no_proxy=*
    restart: "no"
    healthcheck:
      test: "/healthcheck.sh"
      interval: 1s
      retries: 120
      start_period: 120s
      timeout: 120s

networks:
  ddev_default:
    name: ddev_default
    external: true
volumes:
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  {{ if .letsencrypt }}
  ddev-router-letsencrypt:
    name: ddev-router-letsencrypt
  {{ end }}
