services:
  ddev-router:
    image: {{ .router_image }}

    # Prevent zombie container
    init: true
    user: {{ .UID }}:{{ .GID }}

    {{ if and .IsPodman .IsRootless }}
    userns_mode: keep-id
    {{ end }}

    {{ if or .IsPodman .IsRootless }}
    # For: listen tcp :443: bind: permission denied
    cap_add:
      - NET_BIND_SERVICE
    {{ end }}

    networks:
      ddev_default:
        {{ if .Hostnames }}
        aliases:
          {{ range $hostname := .Hostnames }}- "{{ $hostname }}"
          {{ end }}
        {{ end }}

    container_name: ddev-router
    ports: {{ $dockerIP := .dockerIP }}{{ if not .router_bind_all_interfaces }}{{ range $port := .ports }}
      - "{{ $dockerIP }}:{{ $port }}:{{ $port }}"{{ end }}{{ else }}{{ range $port := .ports }}
      - "{{ $port }}:{{ $port }}"{{ end }}{{ end }}
      # Traefik monitor port: Always bind to 127.0.0.1 only for security
      # Use hardcoded 127.0.0.1 instead of $dockerIP because on remote Docker
      # hosts, $dockerIP is the remote IP which cannot be used as a bind address
      - "127.0.0.1:{{.TraefikMonitorPort}}:{{.TraefikMonitorPort}}"
    labels:
      # For cleanup on ddev poweroff
      com.ddev.site-name: ""
    volumes:
      - ddev-global-cache:/mnt/ddev-global-cache:rw
      {{ if .letsencrypt }}
      - ddev-router-letsencrypt:/etc/letsencrypt:rw
      {{ end }} {{/* end if .letsencrypt */}}
    environment:
      - TRAEFIK_MONITOR_PORT={{ .TraefikMonitorPort }}
        {{ if .letsencrypt }}
      - LETSENCRYPT_EMAIL={{ .letsencrypt_email }}
      - USE_LETSENCRYPT={{ .letsencrypt }}
        {{ end }}{{/* end if .letsencrypt */}}
      - TZ={{ .Timezone }}
      # Bypass proxies to allow internal container connections
      - NO_PROXY=*
      - no_proxy=*
    restart: "no"
    healthcheck:
      test: "/healthcheck.sh"
      interval: 1s
      retries: 120
      start_period: 120s
      timeout: 120s

networks:
  ddev_default:
    name: ddev_default
    external: true
volumes:
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  {{ if .letsencrypt }}
  ddev-router-letsencrypt:
    name: ddev-router-letsencrypt
  {{ end }}
