services:
  ddev-router:
    image: {{ .router_image }}

    {{ if eq .Router "traefik" }}
    command:
      - --configFile=/mnt/ddev-global-cache/traefik/static_config.yaml
    user: {{ .UID }}:{{ .GID }}
    {{ end }}

    networks:
        - ddev_default
    container_name: ddev-router
    ports:{{ $dockerIP := .dockerIP }}{{ if not .router_bind_all_interfaces }}{{ range $port := .ports }}
    - "{{ $dockerIP }}:{{ $port }}:{{ $port }}"{{ end }}{{ else }}{{ range $port := .ports }}
    - "{{ $port }}:{{ $port }}"{{ end }}{{ end }}
    {{ if eq .Router "traefik" }}
    # Traefik router; configured in static config as entrypoint
    - "{{ if not .router_bind_all_interfaces }}{{ $dockerIP }}:{{ end }}{{.TraefikMonitorPort}}:{{.TraefikMonitorPort}}"
    {{ end }}
    volumes:
      {{ if ne .Router "traefik" }}
      - /var/run/docker.sock:/tmp/docker.sock:ro
      {{ end }}
      - ddev-global-cache:/mnt/ddev-global-cache:rw
      {{ if .letsencrypt }}
      - ddev-router-letsencrypt:/etc/letsencrypt:rw
      {{ end }} {{/* end if .letsencrypt */}}
    environment:
      - TRAEFIK_MONITOR_PORT={{ .TraefikMonitorPort }}
      - DISABLE_HTTP2={{ .disable_http2 }}
        {{ if .letsencrypt }}
      - LETSENCRYPT_EMAIL={{ .letsencrypt_email }}
      - USE_LETSENCRYPT={{ .letsencrypt }}
        {{ end }}{{/* end if .letsencrypt */}}
    restart: "no"
    healthcheck:
      {{ if eq .Router "traefik" }}
      test: "/healthcheck.sh"
      {{ end }}
      interval: 1s
      retries: 120
      start_period: 120s
      timeout: 120s

networks:
  ddev_default:
    name: ddev_default
    external: true
volumes:
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  {{ if .letsencrypt }}
  ddev-router-letsencrypt:
    name: ddev-router-letsencrypt
  {{ end }}
