services:
  ddev-router:
    image: {{ .router_image }}:{{ .router_tag }}-built
    {{ if not .use_traefik }}
    build:
    {{ else }}
    build:
      context: .
    command:
      - --configFile=/mnt/ddev-global-cache/traefik/static_config.yaml
    {{ end }}

    networks:
        - ddev_default
    {{ if .use_traefik }}
    labels:
      traefik.docker.network: ddev_default
    {{ end }}
    container_name: ddev-router
    ports:{{ $dockerIP := .dockerIP }}{{ if not .router_bind_all_interfaces }}{{ range $port := .ports }}
    - "{{ $dockerIP }}:{{ $port }}:{{ $port }}"{{ end }}{{ else }}{{ range $port := .ports }}
    - "{{ $port }}:{{ $port }}"{{ end }}{{ end }}
    {{ if .use_traefik }}
    # Traefik router; configured in static config as entrypoint
    # TODO: Make this configurable? Put it somewhere else?
    - 9999:9999
    {{ end }}
    volumes:
      {{ if not .use_traefik }}
      - /var/run/docker.sock:/tmp/docker.sock:ro
      {{ end }}
      - ddev-global-cache:/mnt/ddev-global-cache:rw
      {{ if .letsencrypt }}
      - ddev-router-letsencrypt:/etc/letsencrypt:rw
      {{ end }} {{/* end if .letsencrypt */}}
    environment:
      - DISABLE_HTTP2={{ .disable_http2 }}
        {{ if .letsencrypt }}
      - LETSENCRYPT_EMAIL={{ .letsencrypt_email }}
      - USE_LETSENCRYPT={{ .letsencrypt }}
        {{ end }}{{/* end if .letsencrypt */}}
    restart: "{{ if .AutoRestartContainers }}always{{ else }}no{{ end }}"
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 120s
      timeout: 120s

networks:
  ddev_default:
    name: ddev_default
    external: true
volumes:
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  {{ if .letsencrypt }}
  ddev-router-letsencrypt:
    name: ddev-router-letsencrypt
  {{ end }}
