#!/bin/bash

## Usage: ddev one [two three four five]
## Description: This is one's description

echo "This is number one"

echo "ARGS=$@"
echo "DOCROOT=$DDEV_APPROOT"
echo "PHP_VERSION=$DDEV_PHP_VERSION"

exit 1

