#!/usr/bin/env bash

## #ddev-generated
## Description: Display Varnish logs in Apache / NCSA combined log format
## Usage: varnishncsa [flags] [args]
## Example: "ddev varnishncsa"

# This example runs inside the varnish container.
# Note that this requires that /mnt/ddev_config be mounted
# into the varnish container.

varnishncsa "$@"
