#!/usr/bin/env bash

## #ddev-generated
## Description: Display Varnish logs
## Usage: varnishlog [flags] [args]
## Example: "ddev varnishlog"

# This example runs inside the varnish container.
# Note that this requires that /mnt/ddev_config be mounted
# into the varnish container.

varnishlog "$@"
