#!/usr/bin/env bash

## #ddev-generated
## Description: Control a running Varnish instance
## Usage: varnishadm [flags] [args]
## Example: "ddev varnishadm"

# This example runs inside the varnish container.
# Note that this requires that /mnt/ddev_config be mounted
# into the varnish container.

varnishadm "$@"
