  - command: ".buildkite/test.sh"
    agents:
      - "os=linux,arch=arm64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
    parallelism: 1
