# Docker Desktop on macOS arm64
# See https://buildkite.com/ddev/ddev-macos-arm64-mutagen/settings/repository
# Runs on master and PRs, including forked PRs

  - command: ".buildkite/test.sh"
    plugins:
      - docker-login#v2.1.0:
          username: druddockerpullaccount
          password-env: DOCKERHUB_PULL_PASSWORD
    agents:
      - "os=macos"
      - "docker-desktop=true"
      - "architecture=arm64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "true"
      DDEV_RUN_GET_TESTS: "true"
      DOCKER_TYPE: "docker-desktop"

    parallelism: 1
