# Docker Desktop on macOS amd64
# See https://buildkite.com/ddev/ddev-macos-amd64-mutagen/settings/repository
# Runs on master only

  - command: ".buildkite/test.sh"
    plugins:
      - docker-login#v2.1.0:
          username: druddockerpullaccount
          password-env: DOCKERHUB_PULL_PASSWORD
    agents:
      - "os=macos"
      - "docker-desktop=true"
      - "architecture=amd64"
    branches: "master"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "true"
      DOCKER_TYPE: "docker-desktop"
    parallelism: 1
