  - command: ".buildkite/test_containers.sh"
    agents:
      - "os=macos"
      - "dockertype=dockerformac"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
    parallelism: 1
