# Colima with VZ and virtiofs
# See https://buildkite.com/ddev/macos-colima-vz/settings/repository
# Runs on main and PRs, including forked PRs

  - command: ".buildkite/test.sh"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=macos"
      - "colima=true"
      - "colima_vz=true"
      - "architecture=arm64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "false"
      DDEV_RUN_GET_TESTS: "false"
      DOCKER_TYPE: "colima_vz"
      LIMA_SSH_PORT_FORWARDER: "true"
    parallelism: 1
