# macOS Lima on arm64 with VZ/Virtiofs
# See https://buildkite.com/ddev/macos-lima/settings/repository
# Runs on master and PRs, including forked PRs

  - command: ".buildkite/test.sh"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=macos"
      - "lima=true"
      - "architecture=arm64"
#    branches: "none"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "false"
      DDEV_RUN_GET_TESTS: "false"
      DOCKER_TYPE: "lima"
      LIMA_SSH_PORT_FORWARDER: "true"
    parallelism: 1
