# Docker Desktop on macOS arm64
# See https://buildkite.com/ddev/ddev-macos-arm64-mutagen/settings/repository
# Runs on main and PRs, including forked PRs

  - command: ".buildkite/test.sh"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=macos"
      - "docker-desktop=true"
      - "architecture=arm64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "true"
      DOCKER_TYPE: "docker-desktop"
      # /opt/homebrew/etc/buildkite-agent/hooks/environment
      # DOCKERHUB_PULL_USERNAME
      # DOCKERHUB_PULL_PASSWORD
      # DDEV_GITHUB_TOKEN
    parallelism: 1
