# Orbstack on macOS arm64
# See https://buildkite.com/ddev/macos-orbstack/settings/repository
# Runs on main and PRs, including forked PRs

  - command: ".buildkite/test.sh"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=macos"
      - "orbstack=true"
      - "architecture=arm64"
#    branches: "main"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "false"
      DDEV_RUN_GET_TESTS: "false"
      DOCKER_TYPE: "orbstack"
    parallelism: 1
