# Colima with qemu and sshfs
# See https://buildkite.com/ddev/macos-colima/settings/repository
# Runs on master and PRs, including forked PRs

  - command: ".buildkite/test.sh"
    agents:
      - "os=macos"
      - "colima=true"
      - "architecture=arm64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "false"
      DDEV_RUN_GET_TESTS: "false"
      DOCKER_TYPE: "colima"
    parallelism: 1
