  - command: ".buildkite/test.sh"
    agents:
      - "os=macos"
      - "dockertype=dockerformac"
      - "architecture=arm64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_USE_NFSMOUNT: true
    parallelism: 1
