# Windows native with Mutagen, used by ddev-windows-mutagen
# See https://buildkite.com/ddev/ddev-windows-mutagen/settings/repository
# Runs on main and PRs, not including forked PRs

  - command: ".buildkite/test.cmd"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=windows"
      - "docker-desktop=true"
      - "architecture=amd64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      DOCKER_TYPE: dockerforwindows
      # C:\buildkite-agent\hooks\environment
      # DOCKERHUB_PULL_USERNAME
      # DOCKERHUB_PULL_PASSWORD
    parallelism: 1
