# Windows native with Mutagen, used by ddev-windows-mutagen
# See https://buildkite.com/ddev/ddev-windows-mutagen/settings/repository
# Runs on master and PRs, not including forked PRs

  - command: ".buildkite/test.cmd"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=windows"
      - "dockertype=dockerforwindows"
      - "architecture=amd64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      DDEV_TEST_USE_NFSMOUNT: false
      DOCKER_TYPE: dockerforwindows
    parallelism: 1
