# Windows installer test pipeline
# This runs the testwininstaller target exclusively on Windows agents
# Uses agent tag 'installer-test=true' for agents that can run installer tests
# Runs exclusively (not concurrent with regular tests)

steps:
  - command: ".buildkite/test-installer.cmd"
    label: "Windows Installer Test"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=windows"
      - "installer-test=true"
      - "architecture=amd64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      DDEV_TEST_USE_REAL_INSTALLER: true
      DDEV_NO_INSTRUMENTATION: true
      CONCURRENCY_GROUP_DEBUG: "windows-tests-$${BUILDKITE_AGENT_ID}-$${BUILDKITE_AGENT_NAME}-$${COMPUTERNAME}"
    timeout_in_minutes: 35
    parallelism: 1
    concurrency: 1
    concurrency_group: "windows-tests-$${BUILDKITE_AGENT_ID}"
