# Not currently used. This would build and run containers on Windows.

  - command: ".buildkite/test_containers.cmd"
    agents:
      - "os=windows"
      - "dockertype=dockerforwindows"
      - "architecture=amd64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      DOCKER_TYPE: dockerforwindows
    parallelism: 1
