# Build and run containers on Windows.
# Not currently used.

  - command: ".buildkite/test_containers.cmd"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=windows"
      - "dockertype=dockerforwindows"
      - "architecture=amd64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      DOCKER_TYPE: dockerforwindows
    parallelism: 1
