# WSL2 Mirrored Mode networking with docker-ce (docker native inside WSL2 == Docker inside)
# See https://buildkite.com/ddev/wsl2-mirrored/settings/repository
# Runs on main and PRs

  - command: ".buildkite/test.sh"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=wsl2-mirrored"
      - "architecture=amd64"
      - "dockertype=wsl2"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DOCKER_TYPE: "wsl2dockerinside"
    parallelism: 1
