# WSL2 with docker-ce (docker native inside WSL2 == Docker inside)
# See https://buildkite.com/ddev/wsl2-docker-inside/settings/repository
# Runs on master and all PRs, including forked PRs

  - command: ".buildkite/test.sh"
    plugins:
      - docker-login#v2.1.0:
          username: druddockerpullaccount
          password-env: DOCKERHUB_PULL_PASSWORD
    agents:
      - "os=wsl2"
      - "architecture=amd64"
      - "dockertype=wsl2"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
    parallelism: 1

