# WSL2 using Docker Desktop
# See https://buildkite.com/ddev/wsl2-docker-desktop/settings/repository
# Runs on master and PRs, not including forked PRs

  - command: ".buildkite/test.sh"
    if: |
      build.message !~ /\[(skip ci|skip buildkite)\]/
    agents:
      - "os=wsl2"
      - "architecture=amd64"
      - "dockertype=dockerforwindows"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
      DDEV_TEST_SHARE_CMD: "true"
      DOCKER_TYPE: "wsl2-docker-desktop"
    parallelism: 1
