#!/usr/bin/env bash

#ddev-generated
<<'###YAML_ANNOTATIONS'
description: "Run artisan CLI inside the web container"
usage: "artisan [flags] [args]"
example: '"ddev artisan list" or "ddev artisan cache:clear"'
aliases:
  - "art"
projectTypes:
  - "laravel"
execRaw: true
mutagenSync: true
###YAML_ANNOTATIONS

php ./artisan "$@"
