#!/usr/bin/env bash

#ddev-generated
## Description: Run asterios CLI inside the web container
## Usage: asterios [flags] [args]
## Example: "ddev asterios list" or "ddev asterios view:clear"
## ProjectTypes: asterios
## ExecRaw: true
## MutagenSync: true

cd "${DDEV_COMPOSER_ROOT:-/var/www/html}" || exit 1
php ./asterios "$@"
