#!/usr/bin/env bash

#ddev-generated
<<'###YAML_ANNOTATIONS'
description: "Run cake CLI inside the web container"
usage: "cake [subcommand] [flags] [args]"
example: '"ddev cake bake" or "ddev cake cache clear_all"'
projectTypes:
  - "cakephp"
execRaw: true
mutagenSync: true
###YAML_ANNOTATIONS

php ./bin/cake.php "$@"

