#!/bin/bash

#ddev-generated
<<'###YAML_ANNOTATIONS'
description: "Run symfony console inside the web container"
usage: "console [flags] [args]"
example: '"ddev console about" or "ddev console doctrine:schema:update --dump-sql"'
projectTypes:
  - "symfony"
execRaw: true
mutagenSync: true
###YAML_ANNOTATIONS

if [ ! -f bin/console ]; then
  echo 'bin/console does not exist in your project root directory.'
  echo 'Please verify that you installed symfony in your project directory.'
  exit 1
fi

symfony console "$@"
