#!/bin/bash

#ddev-generated
## Description: Run magento CLI inside the web container
## Usage: magento [flags] [args]
## Example: "ddev magento list" or "ddev magento maintenance:enable" or "ddev magento sampledata:reset"
## ProjectTypes: magento2

if ! command -v magento >/dev/null; then
  echo 'magento is not available in your in-container $PATH'
  exit 1
fi

magento "$@"

