#!/bin/bash

#ddev-generated
## Description: Run Pint inside the web container
## Usage: pint [flags] [args]
## Example: "ddev pint --dirty" for fixing your current changes lint errors or "ddev pint --test app/Models" for only analyzing your models without autofix. 
## ProjectTypes: laravel

if ! command -v pint >/dev/null; then
  echo "pint is not available. You may need to 'ddev composer require laravel/pint'"
  exit 1
fi

pint "$@"

