#!/usr/bin/env bash

#ddev-generated
## Description: Run Silverstripe sake CLI inside the web container
## Usage: sake [flags] [args]
## Example: "ddev sake dev/build" or "ddev sake dev/tasks"
## ProjectTypes: silverstripe
## ExecRaw: true
## MutagenSync: true

# Ignore anything we find in the mounted global commands
PATH=${PATH//\/mnt\/ddev-global-cache\/global-commands\/web/}

sake "$@"

