#!/usr/bin/env bash

#ddev-generated
## Description: Run spark CLI inside the web container
## Usage: spark [flags] [args]
## Example: "ddev spark list" or "ddev spark cache:clear"
## ProjectTypes: codeigniter
## ExecRaw: true
## MutagenSync: true

cd "${DDEV_COMPOSER_ROOT:-/var/www/html}" || exit 1
php ./spark "$@"
