name: 🐞 Bug report
description: Create a report to help us improve.
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Run a Diagnostic and Paste Link Here
      description: |
        If you're having trouble with ddev,

        1. Please use the latest stable version of DDEV-Local before reporting. Upgrading is easy see https://github.com/drud/ddev/releases/latest.
        2. Please run a quick diagnostic and post the results as a new gist on gist.github.com (or on another pastebin-type site if you prefer). Just run `ddev debug test` and post the results as a gist on https://gist.github.com. That will help so we don't have to ask so many questions... And if it works, it probably means there's something wrong with your project, not ddev. Put the link to the gist here, thanks. (If you don't yet have the `ddev debug test` command, you can download [test_ddev.sh](https://raw.githubusercontent.com/drud/ddev/master/cmd/ddev/cmd/scripts/test_ddev.sh) and run it with the instructions at the top.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
