name: 🐞 Bug report or Support Request
description: Create a report to help us improve.
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Preliminary checklist
      description: Please complete the following checks before submitting an issue.
      options:
        - label: I am using the latest stable version of DDEV (see [upgrade guide](https://docs.ddev.com/en/stable/users/install/ddev-upgrade/))
          required: true
        - label: I have searched [existing issues](https://github.com/ddev/ddev/issues)
          required: true
        - label: I have checked the [troubleshooting guide](https://docs.ddev.com/en/stable/users/usage/troubleshooting/)
          required: true
        - label: I have run `ddev utility test` or at least `ddev utility diagnose` to include output below
          required: true

  - type: textarea
    attributes:
      label: Output of `ddev utility test` or `ddev utility diagnose`
      value: |
        <details><summary>Expand `ddev utility test` diagnostic information</summary>
        
        ```
        [COPY-PASTE HERE THE OUTPUT OF `ddev utility test`]
        ```
        </details>
      description: |
        Whether you’re having trouble or not, help us with context that will skip a bunch of questions we'd have to ask afterwards:

        1. Make sure you’re on the [latest stable version](https://github.com/ddev/ddev/releases/latest) before reporting, [upgrading](https://docs.ddev.com/en/stable/users/install/ddev-installation/) if necessary.
        2. Run a diagnostic and post the results as a new Gist (or your favorite equivalent). Run `ddev utility test`, and share a link to the results via https://gist.github.com. (If this works, there may not be something wrong with DDEV but something to [troubleshoot in your project](https://docs.ddev.com/en/stable/users/usage/troubleshooting/).)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Specific steps to reproduce the behavior.
      placeholder: |
        1. In this environment... 
        2. With this config... 
        3. Run `...` 
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Screenshots? Anything that will give us more context about your issue!

        💡 Attach images or log files by clicking this area to highlight it and dragging files in.
    validations:
      required: false
