blank_issues_enabled: false
contact_links:
  - name: 💬 DDEV Community Discord
    url: https://ddev.com/s/discord
    about: Join the DDEV Community to talk, exchange experiences or ask and answer questions.
  - name: 💙 Sponsor DDEV
    url: https://ddev.com/sponsor
    about: DDEV is free and open source, funded by its community. Consider sponsoring to help keep it independent.

