#!/usr/bin/env bash

#ddev-generated
# load bash completion for npm if it is not declared
if ! declare -F _npm_completion >/dev/null; then
  [ -n "$(type -t npm)" ] && eval "$(npm completion)"
fi
# set env variables required for npm's bash completion script
COMP_WORDS=("$@")
COMP_CWORD=$(($# - 1))
# run the actual script
_npm_completion
# output the result (which was stored in COMPREPLY) as a new-line delimited string
printf "%s\n" "${COMPREPLY[@]}"
