#!/usr/bin/env bash

## #ddev-generated
## Description: run mariadb client in db container with 'root' user privileges
## Usage: mariadb [flags] [args]
## Example: "ddev mariadb" or "ddev mariadb -udb -pdb" or "echo 'SHOW TABLES;' | ddev mariadb"
## `ddev mariadb --database=mariadb -udb -pdb` gets you to the 'mariadb' database with 'db' user privileges
## DBTypes: mariadb
## ExecRaw: true

# Pass --skip-ssl when the client supports it (DDEV db server does not provide SSL, issue #8119)
SKIP_SSL=""
if command -v mariadb >/dev/null 2>&1; then
    if mariadb --help 2>&1 | grep -q -- '--skip-ssl'; then SKIP_SSL="--skip-ssl"; fi
    exec mariadb $SKIP_SSL "$@"
else
    if mysql --help 2>&1 | grep -q -- '--skip-ssl'; then SKIP_SSL="--skip-ssl"; fi
    exec mysql $SKIP_SSL "$@"
fi
