#!/usr/bin/env bash

## #ddev-generated
## Description: run mysql client in db container with 'root' user privileges
## Usage: mysql [flags] [args]
## Example: "ddev mysql" or "ddev mysql -udb -pdb" or "echo 'SHOW TABLES;' | ddev mysql"
## `ddev mysql --database=mysql -udb -pdb` gets you to the 'mysql' database with 'db' user privileges
## DBTypes: mysql,mariadb
## ExecRaw: true

# Prefer 'mariadb' instead of 'mysql' (older versions of MariaDB only have the 'mysql' binary)
if [[ "${DDEV_DATABASE}" == "mariadb"* ]] && command -v mariadb >/dev/null 2>&1; then
    mariadb "$@"
else
    mysql "$@"
fi
