#!/usr/bin/env bash

## #ddev-generated
## Description: run mysql client in db container with 'root' user privileges
## Usage: mysql [flags] [args]
## Example: "ddev mysql" or "ddev mysql -udb -pdb" or "echo 'SHOW TABLES;' | ddev mysql"
## `ddev mysql --database=mysql -udb -pdb` gets you to the 'mysql' database with 'db' user privileges
## DBTypes: mysql,mariadb
## ExecRaw: true

# Pass --skip-ssl when the client supports it (DDEV db server does not provide SSL, issue #8119)
SKIP_SSL=""
if [[ "${DDEV_DATABASE}" == "mariadb"* ]] && command -v mariadb >/dev/null 2>&1; then
    if mariadb --help 2>&1 | grep -q -- '--skip-ssl'; then SKIP_SSL="--skip-ssl"; fi
    exec mariadb $SKIP_SSL "$@"
else
    if mysql --help 2>&1 | grep -q -- '--skip-ssl'; then SKIP_SSL="--skip-ssl"; fi
    exec mysql $SKIP_SSL "$@"
fi
