#!/usr/bin/env bash

## #ddev-generated
## Description: run mysql client in db container with 'root' user privileges
## Usage: mysql [flags] [args]
## Example: "ddev mysql" or "ddev mysql -udb -pdb" or "echo 'SHOW TABLES;' | ddev mysql"
## `ddev mysql --database=mysql -udb -pdb` gets you to the 'mysql' database with 'db' user privileges
## DBTypes: mysql,mariadb
## ExecRaw: true

mysql "$@"
