package cmd

// RegisterCommands builds the built-in ddev command tree explicitly,
// replacing the implicit, file-order-dependent registration these commands
// used to do via their own init() functions. It only adds built-in
// commands and their flags - it does not touch Docker, the filesystem, or
// any project state. Called from Setup(), which also adds custom/provider
// commands; cmd/ddev_gen_autocomplete calls Setup() rather than this
// directly, to match the full command tree a real ddev invocation builds.
func RegisterCommands() {
	registerAddonGetCmd()
	registerAddonListCmd()
	registerAddonRemoveCmd()
	registerAddonSearchCmd()
	registerAddonUpdateCmd()
	registerAddonCmd()
	registerAliasesCmd()
	registerAuthSSHCmd()
	registerAuthCmd()
	registerCleanCmd()
	registerCmdVersionCmd()
	registerComposerCreateProjectCmd()
	registerComposerCmd()
	registerConfigGlobalCmd()
	registerConfigCmd()
	registerDebugCdCmd()
	registerDebugCheckDBMatchCmd()
	registerDebugComposeConfigCmd()
	registerDebugConfigYamlCmd()
	registerDebugDeleteVolumeCmd()
	registerDebugDownloadImagesCmd()
	registerDebugFixcommandsCmd()
	registerDebugGetVolumeDBVersionCmd()
	registerDebugGobDecodeCmd()
	registerDebugInstrumentationCleanCmd()
	registerDebugInstrumentationFlushCmd()
	registerDebugInstrumentationCmd()
	registerDebugMatchConstraintCmd()
	registerDebugMessageConditionsCmd()
	registerDebugMigrateDatabaseCmd()
	registerDebugMutagenCmd()
	registerDebugRebuildCmd()
	registerDebugRemoteDataCmd()
	registerDebugTestCmd()
	registerDebugTestcleanupCmd()
	registerDebugCmd()
	registerDeleteImagesCmd()
	registerDeleteCmd()
	registerDescribeCmd()
	registerDotenvGetCmd()
	registerDotenvSetCmd()
	registerDotenvCmd()
	registerExecCmd()
	registerExportDBCmd()
	registerGetCmd()
	registerHostnameCmd()
	registerImportDBCmd()
	registerImportFilesCmd()
	registerListCmd()
	registerLogsCmd()
	registerMutagenLogsCmd()
	registerMutagenMonitorCmd()
	registerMutagenResetCmd()
	registerMutagenStatusCmd()
	registerMutagenSyncCmd()
	registerMutagenVersionCmd()
	registerMutagenCmd()
	registerPoweroffCmd()
	registerPullCmd()
	registerPushCmd()
	registerRestartCmd()
	registerShareCmd()
	registerSnapshotCmd()
	registerSnapshotRestoreCmd()
	registerSSHCmd()
	registerStartCmd()
	registerStopCmd()
	registerTuiCmd()
	registerUtilityAddonUpdateCheckerCmd()
	registerUtilityCheckCustomConfigCmd()
	registerUtilityDiagnoseCmd()
	registerUtilityDockercheckCmd()
	registerUtilityDownloadDdevCmd()
	registerUtilityMutagenDiagnoseCmd()
	registerUtilityPortDiagnoseCmd()
	registerUtilityTLSDiagnoseCmd()
	registerUtilityXdebugDiagnoseCmd()
	registerXhguiCmd()
}
