#!/bin/bash

## #ddev-generated
## Description: run mysql client in web container
## Usage: mysql [flags] [args]
## Example: "ddev mysql" or "ddev mysql -uroot -proot -hdb" or "echo 'SHOW TABLES;' | ddev mysql"
## `ddev mysql mysql -uroot -proot` gets you to the 'mysql' database with root privileges

mysql -udb -pdb -hdb $@
