// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "38809f1ea553e1f71ca4cb178afb1a1e"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"0cac625b2c6c4b81ef7d24fe7b809bdd": "1f8b08000000000000ff6c8d414b33311086eff915efd7fd604f4befeb45c58207c143150fa5d064332681348999d9d6823f5eb6abb0072f330cf3bccfdbfc5b9b90d646b357aa69f0403cd45024e4d4a38e09c70b7f440c315012848433190c39890e89ea947865eda8ffe176ef513bde63a7abe3fdf4de7cea6389d463652d9d666c855c9737bab1e62ce8cabcbc35334283cf68b78fcf6f78b9bb7fda6c6f5a7c61219a1a0e0bd11fba031c09e39247488678427ba55a582dda68269c83785c23a5865388e48895fa755983ae4cc35b83ffb7ea3b0000ffffdf3e65a733010000",
		"1728ad260a238e2c2fdfd24ab114e968": "1f8b08000000000000ff2cca310e42210c00d0bda7a81f777626074f60e2641c0a6da04b312d787e63747e2f9d7255cb956200a484f7a02e0599e58dec3b063ec87b3cbf769568aeafa5d30adeb6fd835a280bae21d8a62d521307f8d971be1cf0090000ffff95d5f0d064000000",
		"1e0cc38e0d7a68229c0bd7b0d230b0d7": "1f8b08000000000000ffa48ecd4ac3401485f7f314c724b4ba98fee8426811b4a4d08550b1551722ed4c72930ca43371665229eabbcbc482ee5cb83977f39defdcf86428951e4ae12ac6e21829b9ccaac62ba327b0adc6eee05e6b64b522ed61342ae37c001f9c2869826d9ed3fe1bdaa2301652389541641939076fb0134a23175e48e108a7b93c0bed5fb563720ede5a633c7813ce16257987836983c557847e07f67f646fca57e82a8d557b555349ae9353561944abc5f209eb9bd9ed7c358df081bf271913b67457512e23a60a3c2389c14bc2082fd3f08266404724d7ac508cc5ddd051d6e612bc09518dcf2f07a3c1683006e78db11ec97b9ace1f378be56abd49679bbbe5fd7ac23f9104197a3db89aa8c105fba78a7d050000ffff1fc7893fce010000",
		"36a9eea9ce771395444039dd09560938": "1f8b08000000000000ff5256d44fcaccd34f4a2ccee0e24a4dcec857500ac9c82c56c82c56c82bcd4d4a2d522829cf575250535348adc82c5130e202040000fffffcf174d431000000",
		"4bc6fb5693438105e7497305ebd1bbcb": "1f8b08000000000000ff5256d44fcaccd34f4a2ccee0e252565670492d4e2eca2c28c9cccfb352c82a2d2e51282acd2b5648292a2dce50282eccd14dcec95448cb2f52a8cc2fe5e24a4dcec857500a0877b1550908775182f2c333124b1452f215ca5341645e7eb9bd12178a015c80000000ffff7ee0161376000000",
		"f6528e08079092b9733298067e67b2ea": "1f8b08000000000000ff4c8c4f0b82301887effb146f2a7494ae829034a92e6da8798910ffbcb61dda629bd6c78f8152c7e77d9ef7176ee24eaab86bad20240ce16adb0726300c3883560837f7d6e0844184514f064639e3dd87146d6fe4cb49ad12a884b420adffd85a187e8a10ec8586600dd4f4ecd0f82e5855561ccb34da070b52762818abd288d2bc6e32ce3dad929f7853e74579669725f8bbf8c58f74b023e41b0000ffffebe89f31d6000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("customcommands", "./assets")
		b.SetResolver("commands/db/mysql", packr.Pointer{ForwardBox: gk, ForwardPath: "0cac625b2c6c4b81ef7d24fe7b809bdd"})
		b.SetResolver("commands/host/mysql.example", packr.Pointer{ForwardBox: gk, ForwardPath: "1e0cc38e0d7a68229c0bd7b0d230b0d7"})
		b.SetResolver("commands/host/one", packr.Pointer{ForwardBox: gk, ForwardPath: "f6528e08079092b9733298067e67b2ea"})
		b.SetResolver("commands/host/sql-cli", packr.Pointer{ForwardBox: gk, ForwardPath: "4bc6fb5693438105e7497305ebd1bbcb"})
		b.SetResolver("commands/host/two", packr.Pointer{ForwardBox: gk, ForwardPath: "36a9eea9ce771395444039dd09560938"})
		b.SetResolver("commands/web/drush", packr.Pointer{ForwardBox: gk, ForwardPath: "1728ad260a238e2c2fdfd24ab114e968"})
		}()

	return nil
}()
