#!/usr/bin/env bash

## #ddev-generated
## Description: Test program for Varnish
## Usage: varnishtest [flags] [args]
## Example: "ddev varnishtest"

# This example runs inside the varnish container.
# Note that this requires that /mnt/ddev_config be mounted
# into the varnish container.

varnishtest "$@"
