#!/bin/bash

#ddev-generated
## Description: Run PHIVE inside the web container
## Usage: phive [flags] [args]
## Example: "phive install phpunit"

if ! command -v phive >/dev/null; then
  echo "phive is not available"
  exit 1
fi
phive "$@"
