#!/bin/bash

## Description: testcmd for flags with duplicate shorthand
## Usage: testflagsduplicateshorthand
## Flags: [{"Long":"test-1","Short":"t","Usage":"Usage of test 1"},{"Long":"test-2","Short":"t","Usage":"Usage of test 2 with existing shorthand"}]
## Example: "ddev testflagsduplicateshorthand"
