#!/bin/bash

## Description: testcmd for flags with duplicate flag
## Usage: testflagsduplicate
## Flags: [{"Long":"test-1","Short":"t","Usage":"Usage of test 1"},{"Long":"test-1","Usage":"Test duplicate"}]
## Example: "ddev testflagsduplicate"
