version: '2'

services:
  db:
    container_name: local-test-db
    image: DDEV_DBIMAGE
    volumes:
      - "./data:/db"
    restart: always
    environment:
      - TCP_PORT=DDEV_HOSTNAME:3306
    ports:
      - 3306
    labels:
      com.ddev.site-name: test
      com.ddev.platform: local
      com.ddev.app-type: wordpress
  web:
    container_name: local-test-web
    image: DDEV_WEBIMAGE
    volumes:
      - "../htdocs/:/var/www/html/docroot"
    restart: always
    depends_on:
      - db
    links:
      - db:DDEV_HOSTNAME
      - db:db
    ports:
      - "80"
      - 8025
    working_dir: "/var/www/html/docroot"
    environment:
      - DEPLOY_NAME=local
      - VIRTUAL_HOST=DDEV_HOSTNAME
      - VIRTUAL_PORT=80,8025
    labels:
      com.ddev.site-name: test
      com.ddev.platform: local
      com.ddev.app-type: wordpress
networks:
  default:
    external:
      name: ddev_default
