name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:

  build:
    name: Build DDEV executables
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          # We need to get all branches and tags for git describe to work properly
          fetch-depth: 0

      - name: Install Docker and deps
        run: ./.github/workflows/linux-setup.sh

      - name: Install build tools
        run: ./.github/workflows/linux-build-setup.sh

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.3'
      
      # Install Node v10 for the staticrequired step
      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      #- name: staticrequired
      #  run: make staticrequired

      - name: Build DDEV executables
        run: make linux_amd64 linux_arm64 darwin_amd64 windows_amd64 windows_install

      - name: Generate artifacts
        run: ./.github/workflows/generate_artifacts.sh ${{ github.workspace }}/artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ddev-executables
          path: ${{ github.workspace }}/artifacts/*
          # 90 retention days are overkill for this
          retention-days: 7

      - name: Upload .gotmp/bin folder
        uses: actions/upload-artifact@v2
        with:
          name: ddev-gotmp-bin
          path: ${{ github.workspace }}/.gotmp/bin/*
          # 90 retention days are overkill for this
          retention-days: 7

  tests:
    needs: build
    name: ${{ matrix.os }} - ${{ matrix.webserver }} - make ${{ matrix.tests }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        webserver: [apache-fpm, nginx-fpm]
        tests: [testcmd, testnotddevapp, testddevapp]
        os: [ubuntu-20.04, macos-11.0]
      fail-fast: false

    env:
      DDEV_TEST_WEBSERVER_TYPE: ${{ matrix.webserver }}
      DRUD_NONINTERACTIVE: "true"

    steps:
      - uses: actions/checkout@v2

      # Experiment with only testing TYPO3 with the apache run.
      - name: GOTEST_SHORT on Apache
        if: matrix.webserver == 'apache-fpm'
        run: echo "GOTEST_SHORT=5" >> $GITHUB_ENV 

      - name: Install Docker and deps (Linux)
        if: matrix.os == 'ubuntu-20.04'
        run: ./.github/workflows/linux-setup.sh
      
      - name: Install Docker and deps (macOS)
        if: matrix.os == 'macos-20.04'
        run: ./.github/workflows/macos-setup.sh  

      - uses: actions/setup-go@v2
        with:
          go-version: 1.*

      - uses: actions/download-artifact@v2
        with:
          name: ddev-gotmp-bin
          path: .gotmp/bin

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .gotmp/bin

      - name: DDEV tests
        run: |
          if [[ "${{ matrix.os }}" == macos* ]]; then
            eval "$(docker-machine env default)"
          fi
          make ${{ matrix.tests }}
        timeout-minutes: 120

      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: ddev-test-results-apache-fpm
          path: /tmp/testresults/
