name: MacOS tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:

  container-tests:
    name: Container tests
    runs-on: macos-latest

    steps:
      - name: Install Docker
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install make docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default

      - uses: actions/checkout@v2

      - name: Run container tests
        run: |
          eval "$(docker-machine env default)"
          docker version
          set -eu -o pipefail
          for dir in containers/*/
              do pushd $dir
              echo "--- Build container $dir"
              time make container DOCKER_ARGS=--no-cache
              echo "--- Test container $dir"
              time make test
              popd
          done
          set +eu

  ddev-tests:
    name: DDEV tests
    runs-on: macos-latest

    steps:
      - name: Install Docker
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install make docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default

      - uses: actions/checkout@v2

      - name: Run DDEV tests
        run: |
          eval "$(docker-machine env default)"
          docker version
          echo "Running tests..."
          time make test
          RV=$?
          echo "build.sh completed with status=$RV"
          ddev poweroff || true
          exit $RV
