# This temporary test of nginx.tmpl is here to demonstrate that
# ddev (ddev-router) can now run successfully on github actions linux
on:
  push:
    branches:
    - master
  pull_request:

name: test ddev-router's nginx.tmpl generation

jobs:
  test:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest ]
    steps:
    - uses: actions/checkout@v1
    - name: Set environment variables
      run: printf "OS=$(go env GOOS)\nARCH=$(go env GOARCH)\n" >> $GITHUB_ENV && cat $GITHUB_ENV
    - name: macOS setup
      if: env.OS == 'darwin'
      run: .github/workflows/macos_github_vm_setup.sh
    - run: make
    - run: sudo cp .gotmp/bin/${OS}_${ARCH}/ddev /usr/local/bin
    - run: sudo curl --fail -lL -s -o /usr/local/bin/mkcert https://github.com/drud/mkcert/releases/download/v1.4.6/mkcert-v1.4.6-${OS}-${ARCH} && sudo chmod +x /usr/local/bin/mkcert && mkcert -install
    - run: ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
    - run: cd testsite && ddev config --project-type=php && ddev start
    - run: docker inspect --format "{{json .State.Health }}" ddev-router | jq -r .Log[-1].Output | grep "ddev-router is healthy with 2 upstreams"
    #      - uses: mxschmitt/action-tmate@v3
    - run: curl --fail -s https://testsite.ddev.site | grep "This is testsite" || curl https://testsite.ddev.site
    - run: .github/workflows/multiplesites.sh

