name: PR Check

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review, review_requested]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  check_pr_title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(build|chore|ci|docs|feat|fix|perf|refactor|style|test)(\([a-z][a-z0-9-]*\))?!?:\s(?!.*  )[a-z](?:[ \w.''"`\\\/\-\(\)\[\],])*[A-Za-z0-9\]\)''"`](?:, (?:fixes|for) #\d+)*$'
          flags: ''
          excludeDescription: true
          error: 'Title does not follow our conventions see https://ddev.readthedocs.io/en/latest/developers/building-contributing/#pull-request-title-guidelines'

  assign_labels:
    name: Assign Labels
    needs: check_pr_title
    runs-on: ubuntu-latest
    steps:
      - name: Assign and check labels
        uses: fuxingloh/multi-labeler@v4
        with:
          config-path: .github/pr-labeler.yml
