name: Spellcheck docs
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Spellcheck docs
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 2
    - uses: ./docs
      with:
        bucket: .github/actions
        project: spelling
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
