name: Spellcheck docs
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.8.0
      name: Spellcheck
