name: Windows tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  global:
    - BUILDKIT_PROGRESS=plain

jobs:

  container-tests:
    name: Container tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./.github/workflows/test_containers.cmd
