name: Windows tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  container-tests:
    name: Container tests
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-make
          path-type: inherit
      - name: CI-Build
        env:
          BUILDKIT_PROGRESS: plain
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          echo 'Running in MSYS2!'
          ./.github/workflows/test_containers.sh
