name: Windows tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:

  container-tests:
    name: Container tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker buildx
        run: |
          docker pull minio/minio
          ls C:\ProgramData\Docker\cli-plugins
          Restart-Service docker
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make
          path-type: inherit
      - name: CI-Build
        shell: msys2 {0}
        run: |
          echo 'Running in MSYS2!'
          docker version
          ./.github/workflows/test_containers.sh
